project:
  type: website

website:
  title: "MDA Team Wiki"
  repo-url: https://github.com/ruralinnovation/wiki
  repo-actions: [edit, issue]
  navbar:
    logo-href: https://ruralinnovation.us/our-work/research_mapping/
    left:
      - href: index.qmd
        text: MDA Team Wiki
      - href: profile/about.qmd
        text: About
#  sidebar:
#    style: "docked"
#    search: true
#    contents:
#      - section: "Capabilities & Knowledge"
      - text: "Capabilities & Knowledge"
#        contents:
        menu:
#          - section: "Applications"
#            contents:
#              - BEAD-Changelog.qmd
          - Broadband.qmd
          - Census.qmd
          - CORI-Ontology.qmd
#          - Research.qmd (TODO)
#      - section: "Infrastructure"
      - text: "Infrastructure"
#        contents:
        menu:
          - Ansible.md
          - CORI-Data-API.qmd
          - MDA-Data-Infrastructure-Overview.qmd
          - Data-Security.qmd
          - duckDB.qmd
          - PostgreSQL-RDS-Management.md
          - R-DBI-GDAL-PG-SF.qmd
          - Repository-Classification.md
          - Metadata.md
          - Styles-and-Viz.qmd
          - targets.qmd
#      - section: "Team Onboarding"
      - text: "Team Onboarding"
#        contents:
        menu:
          - onboarding_team_db.md
          - QGIS.md
          - The-coriverse-suite-of-packages.md
          - MDA-Style-Guide.md
          - G-Drive-Practice.qmd
          - Git-Workflows.md
          - help_I_have_a_data_team.md
          - Suggested-Code-Snippets.md
          - Spatial-Data-for-Mapping-and-Analysis.md

format:
  html:
    toc: true
    theme:
      - minty
      - src/custom.scss
    css: assets/fonts.css
    fontcolor: "#121E22"
    linkcolor: "#00835D"
    mainfont: "Bitter"
    grid:
      sidebar-width: 250px
      body-width: 1100px
      margin-width: 250px

resources:
  - "assets/*"
