project:
  type: website

website:
  title: "Mapping & Data Analytics @ CORI/RISI"
  repo-url: https://github.com/ruralinnovation/wiki
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: profile/about.qmd
        text: About
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Capabilities & Knowledge"
        contents:
          - Broadband-Consulting-Tech-Requirements.qmd
          - CORI-Ontology.qmd
      - section: "Infrastructure"
        contents:
          - Ansible.md
          - CORI-Data-API.md
#          - section: "CORI Data API"
#            contents:
#              - CORI-Data-API.md
##              - Adding-New-Endpoints-&-Services-to-the-Python-RESTApi.md
##              - Apollo-Studio-Setup.md
##              - Configuring-our-AWS-CLI-(CDK-and-SAM)-Credentials.md
##              - Example-React-Map-Container-with-REACT-MAP-GL-Package.md
##              - Migrating-from-CDK-V1-=--V2.md
##              - Postman-Workspace-Setup-and-Configuration.md
##              - R-and-Python-API-Usage.md
##              - React,-AWS-Amplify-and-API-Usage.md
##              - SAML-User-Pool-IdP-Authentication-Flow.md
##              - Session-2-‐-2023‐10‐23.md
##              - Support-Sessions.md
##              - Working-with-the-GraphQL-Schemas.md
          - Data-Security.qmd
          - duckDB.qmd
          - PostgreSQL-RDS-Managment.md
          - R-DBI-GDAL-PG-SF.qmd
          - Repository-Classification.md
          - Metadata.md
          - targets.qmd
      - section: "Team Onboarding"
        contents:
          - onboarding_team_db.md
          - QGIS.md
          - The-coriverse-suite-of-packages.md
          - MDA-Style-Guide.md
          - G-Drive-Practice.qmd
          - Git-Workflows.md
          - help_I_have_a_data_team.md
          - Suggested-Code-Snippets.md
          - Spatial-Data-for-Mapping-and-Analysis.md

format:
  html:
    theme: minty 
    css: styles.css
    toc: true



